# ATTENTION: ALL CLOUDCANNON CMS CONFIGURATION NOW LIVES IN cloudcannon.config.yml

# ------------------------------------------------
# DEFINE GLOBAL VARIABLES
# ------------------------------------------------

# Site settings
client: TBD
title: Ocupop Project Template
description: This description also used for social share meta
email: dev@ocupop.com
url: "http://client_url.com"
permalink: pretty

# Social sharing
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder


# ------------------------------------------------
# DEFINE COLLECTIONS 
# (All CloudCannon CMS config is set in cloudcannon.config.yml)
# ------------------------------------------------
collections:
  examples:
    output: true
    permalink: /examples/:path/


# ------------------------------------------------
# DEFINE DEFAULT VALUES 
# (useful for setting layout for page types without having them editable by the user)
# ------------------------------------------------
defaults:
  -
    scope:
      type: 'page'
    values:
      layout: default
  -
    scope:
      type: 'post'
    values:
      layout: default
  -
    scope:
      type: 'examples'
    values:
      layout: sandbox
      # variable_name: value
      

# ------------------------------------------------
# BUILD SETTINGS AND PLUGINS
# ------------------------------------------------
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap